### ISSUE TITLE
Peer Review - Lab5a- Angelina Venetto

### ISSUE THREAD

**Issue by avenetto** [aeperusse/progdata-class#2]
Peer Review of Lab 5A file 
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: |  | |
**Presentation: graphs** | :heavy_check_mark: | |  |
**Presentation: tables** | :heavy_check_mark: |  | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *You did a great job of pivoting the data!*
- *Some specific praise?- very good code logic*
- *Something I learned?- nice job figuring out and pivoting correctly! !
- *Specific constructive criticism?-maybe more description of why you are doing each step

**Comment by aeperusse** [comment]
Thank you!
