### ISSUE TITLE
Peer Review of Lab 4 for Allison Perusse

### ISSUE THREAD

**Issue by jayschmidtavendano** [aeperusse/progdata-class#3]
Peer Review of Lab 4 for Allison Perusse
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Overall looks great!*
- *I really like how organized your code is. Everything is labeled and you include indents in your code that make it easier to see what functions you are using as the code progresses*
- *The only thing I would suggest is to add headings to the code chunks, that way the coder is oriented to what you are doing in your code. So you might in code line 12 include "```{r, Read in Data}" just like you did in line 8*

**Comment by aeperusse** [comment]
Thanks for the advice!
