### ISSUE TITLE
Peer Review of Lab 3 for Allison Perusse

### ISSUE THREAD

**Issue by rrorman** [aeperusse/progdata-class#4]
----------------------------------------------------
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | | :heavy_check_mark: | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Great job! Your code ran great! *
- *Maybe add some color to your illustrations? It would be nice to see gdp and life expectancy across different countries. *
- *I learned the usefulness of %in%*
- *The only thing I would work on is labeling your code chunks so they go with the questions. Other than that, great job!*

**Comment by aeperusse** [comment]
Thanks for the feedback!
