### ISSUE TITLE
Peer Review - Sabrina Eisenberg - Lab 2 

### ISSUE THREAD

**Issue by sabeisenberg** [aeperusse/progdata-class#5]
# Peer Review for Allison Perusse's Lab 2 

| Topic | Excellent | Satisfactory | Needs Work |
| ----------- | ----------- | ----------- | ----------- | 
| Coding Style | :heavy_check_mark: |  |  |
| Coding strategy |  | :heavy_check_mark: |  |
| Presentation: graphs |:heavy_check_mark: |  |  |
| Presentation: tables | :heavy_check_mark: |  |  |
| Achievement, creativity | :heavy_check_mark: |  |  |
| Ease of Access | :heavy_check_mark: |  |  |

- Most of your code is very well written! I think it could be helpful to consistently break your code up on to separate lines. For example, the geom_jitter() on line 46 could be on a new line. 
- Good job on your graphs! 
- Good job trying the last exercise, I skipped that in mine.  
- I think it could be useful to break up the parts of the exercises by number (1, 2, 3) instead of editing the code you have to add the next "step" so that you can see the exact progress you made and what you did in each step and why. 
- You only really need to load tidyverse!

**Comment by aeperusse** [comment]
Thanks for the helpful comments!
