### ISSUE TITLE
Peer Review of Lab 06 for Allison - Priya SC

### ISSUE THREAD

**Issue by priyacollins** [aeperusse/progdata-class#6]
Topic | Excellent | Satisfactory | Needs Work |
----------------------------|-----|-----|-----|
**Coding style** | :heavy_check_mark: | | |
**Coding strategy** | :heavy_check_mark: | | |
**Presentation: graphs** | :heavy_check_mark: | | |
**Presentation: tables** | :heavy_check_mark: | | |
**Achievement, creativity** | :heavy_check_mark: | | |
**Ease of access** | :heavy_check_mark: | | |
Remarks:
- *Great job on Lab 06! Your code is easy to read, simple, and organised. My only suggestion would be adding comments to explain what part of the exercise you are filling out, or what the code is doing in context.*

**Comment by aeperusse** [comment]
thanks!!
